name: RecBole-GNN tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        torch-version: [2.0.0]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: true
        auto-activate-base: true
    # install setuptools as a interim solution for bugs in PyTorch 1.10.2 (#69904)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install dgl
        pip install torch==${{ matrix.torch-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install torch_geometric
        pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
        # pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
        pip install recbole==1.1.1
        conda list
        conda install -c conda-forge faiss-cpu
        pip install numpy==1.19
        # conda install -c conda-forge libstdcxx-ng
        # sudo rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        # sudo ln -s /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/lib/gcc/12/libstdc++.so.6.0.30 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        # pip install setuptools==59.5.0
    # Use "python -m pytest" instead of "pytest" to fix imports
    - name: Test model
      run: |
        python -m pytest -v tests/test_model.py
